/**
 * The published demo.
 *
 * `apiUrl` is relative, so the app fetches its data from the same origin it is
 * served from — static JSON generated by `npm run mock:build` and published
 * alongside the bundle. The requests are real HTTP requests, visible in
 * DevTools; only the server answering them is a stand-in.
 */

export const environment = {
  production: true,
  /** No backend behind the demo can answer a login POST, so it is not gated. */
  demoAccess: true,
  apiUrl: 'api/v1/',
};
