import { OrderList } from './order-objects';

export const invoceLists: OrderList[] = [
  {
    id: 101,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 102,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 103,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 104,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 105,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 106,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 107,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 102,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 103,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 104,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 105,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 106,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 107,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 108,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 109,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 110,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 111,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 112,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 113,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 114,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 115,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 116,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 117,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 118,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 119,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 120,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 121,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 122,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 123,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 124,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 125,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 126,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 127,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 128,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 129,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 130,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 131,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 132,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 133,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
  },
  {
    id: 134,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false,
    
  },
  {
    id: 109,
    Name: 'Pineapple Inc.',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false
  },
  {
    id: 135,
    Name: 'PineappleTimes  .',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false
  },
  {
    id: 136,
    Name: 'Fortune Creation',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false
  },
  {
    id: 106,
    Name: 'PineappleTimes  .',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123  },
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false
  },
  {
    id: 137,
    Name: 'Fortune Creation',
    Phone: 979796786,
    order_code: '101',
    city: {id: 1, city_name: 'Ahmedabad', default_price: 123},
    status: 'Shipped',
    status_color: {color: 'bg-success', text_color: 'text-success', class_name: 'badge bg-light-success text-success rounded-pill'},
    date: '2024-10-15',
    Exchange: 'Redq Inc.',
    completed: false
  },
];
